
#include "B3C_HW_TOP_hw_handlers.h"
#include "bionics_const.h"
#include "stdlib.h"
#include "b3c_input_config.h"
#include <B3C_SW_INPUT_MAN.h>

SInputFunctions SInputFuncArr[SYS_NUM_INPUTS]=
    //Init             //SetCalVal                      //GetRawValue                           //GetEngineeringValue                   //GetErrorStatus                //IsIdleStatus                //TriggerScan                    //enable       //disable         
   {{B3C_SM_ADC_MB_Init, &B3C_SM_ADC_MB_SetCalChan0,    &B3C_SM_ADC_MB_GetChan0_Raw,            &B3C_SM_ADC_MB_GetChan0,                B3C_SM_ADC_MB_GetStatus,        B3C_SM_ADC_MB_TransferDone,     NULL,                           B3C_SM_ADC_MB_Enable,   B3C_SM_ADC_MB_Disable},//SYS_INPUT_SM_MB_CH0
    {NULL,               &B3C_SM_ADC_MB_SetCalChan1,    &B3C_SM_ADC_MB_GetChan1_Raw,            &B3C_SM_ADC_MB_GetChan1,                NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SM_MB_CH1
    {NULL,               &B3C_SM_ADC_MB_SetCalChan2,    &B3C_SM_ADC_MB_GetChan2_Raw,            &B3C_SM_ADC_MB_GetChan2,                NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SM_MB_CH2
    {NULL,               &B3C_SM_ADC_MB_SetCalChan3,    &B3C_SM_ADC_MB_GetChan3_Raw,            &B3C_SM_ADC_MB_GetChan3,                NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SM_MB_CH3
    {NULL,               &B3C_SM_ADC_MB_SetCalChan4,    &B3C_SM_ADC_MB_GetChan4_Raw,            &B3C_SM_ADC_MB_GetChan4,                NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SM_MB_CH4
    {NULL,               &B3C_SM_ADC_MB_SetCalChan5,    &B3C_SM_ADC_MB_GetChan5_Raw,            &B3C_SM_ADC_MB_GetChan5,                NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SM_MB_CH5
    {NULL,               &B3C_SM_ADC_MB_SetCalChan6,    &B3C_SM_ADC_MB_GetChan6_Raw,            &B3C_SM_ADC_MB_GetChan6,                NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SM_MB_CH6
    {NULL,               &B3C_SM_ADC_MB_SetCalChan7,    &B3C_SM_ADC_MB_GetChan7_Raw,            &B3C_SM_ADC_MB_GetChan7,                NULL,                           NULL,                           B3C_SM_ADC_MB_ReadTrigger,      NULL,           NULL},//SYS_INPUT_SM_MB_CH7
    {B3C_IMU_SHANK_Init, NULL,                          &B3C_IMU_SHANK_GetLinAccX_Raw,          &B3C_IMU_SHANK_GetLinAccX,              B3C_IMU_SHANK_GetStatus,        B3C_IMU_SHANK_TransfereDone,    NULL,                           NULL,           NULL},//SYS_INPUT_SHANK_LIN_ACC_X
    {NULL,               NULL,                          &B3C_IMU_SHANK_GetLinAccY_Raw,          &B3C_IMU_SHANK_GetLinAccY,              NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SHANK_LIN_ACC_Y
    {NULL,               NULL,                          &B3C_IMU_SHANK_GetLinAccZ_Raw,          &B3C_IMU_SHANK_GetLinAccZ,              NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SHANK_LIN_ACC_Z
    {NULL,               NULL,                          &B3C_IMU_SHANK_GetGravX_Raw,            &B3C_IMU_SHANK_GetGravX,                NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SHANK_LIN_ACC_Z
    {NULL,               NULL,                          &B3C_IMU_SHANK_GetGravY_Raw,            &B3C_IMU_SHANK_GetGravY,                NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SHANK_LIN_ACC_Z
    {NULL,               NULL,                          &B3C_IMU_SHANK_GetGravZ_Raw,            &B3C_IMU_SHANK_GetGravZ,                NULL,                           NULL,                           B3C_IMU_SHANK_ReadTrigger,      NULL,           NULL},//SYS_INPUT_SHANK_LIN_ACC_Z
    {B3C_POS_CT_Init,    &B3C_POS_CT_SetCalAngle,       &B3C_POS_CT_GetAngle_Raw,               &B3C_POS_CT_GetAngle,                   B3C_POS_CT_GetStatus,           B3C_POS_CT_TransfereDone,       NULL,                           NULL,           NULL},//SYS_INPUT_CT_ANGLE
    {NULL,               &B3C_POS_CT_SetCalVirtualGain, &B3C_POS_CT_GetVirtualGain_Raw,         &B3C_POS_CT_GetVirtualGain,             NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_CT_FIELD_MAG
    {NULL,               &B3C_POS_CT_SetCalTorque,      NULL,                                   &B3C_POS_CT_GetTorque,                  B3C_POS_CT_GetStatus,           NULL,                           B3C_POS_CT_ReadTrigger,         NULL,           NULL},//SYS_INPUT_CT_TORQUE
    {B3C_POS_KA_Init,    &B3C_POS_KA_SetCalAngle,       &B3C_POS_KA_GetAngle_Raw,               &B3C_POS_KA_GetAngle,                   B3C_POS_KA_GetStatus,           B3C_POS_KA_TransfereDone,       B3C_POS_KA_ReadTrigger,         NULL,           NULL},//SYS_INPUT_KNEE_ANGLE
    {&B3C_MDB_Init,      NULL,                          &B3C_MDB_GetTorqueActual_Raw,           &B3C_MDB_GetTorqueActual,               B3C_MDB_GetStatus,          B3C_MDB_TransfereDone,          NULL,                           NULL,           NULL},//SYS_INPUT_TORQUE_ACTUAL
    {NULL,               NULL,                          &B3C_MDB_GetCurrent_Raw,                &B3C_MDB_GetCurrent,                    NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_MOTOR_CURRENT
    {NULL,               &B3C_MDB_SetCalMotorTemp,      &B3C_MDB_GetMotorTemp_Raw,              &B3C_MDB_GetMotorTemp,                  NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_MOTOR_TEMP
    {NULL,               NULL,                          &B3C_MDB_GetMosfetTemp_Raw,             &B3C_MDB_GetMosfetTemp,                 NULL,                           NULL,                           B3C_MDB_UpdateTrigger,          NULL,           NULL},//SYS_INPUT_MOSFET_TEMP
    {B3C_HALL_Init,      &B3C_HALL_SetCalZMAG_0,        &B3C_HALL_GetValue_Raw_0,               &B3C_HALL_GetValue_0,                   B3C_HALL_GetStatus,             B3C_HALL_TransfereDone,         NULL,                           B3C_HALL_Enable,        B3C_HALL_Disable},//SYS_INPUT_GCS_0
    {NULL,               &B3C_HALL_SetCalZMAG_1,        &B3C_HALL_GetValue_Raw_1,               &B3C_HALL_GetValue_1,                   NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_GCS_1
    {NULL,               &B3C_HALL_SetCalZMAG_2,        &B3C_HALL_GetValue_Raw_2,               &B3C_HALL_GetValue_2,                   NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_GCS_1
    {NULL,               &B3C_HALL_SetCalZMAG_3,        &B3C_HALL_GetValue_Raw_3,               &B3C_HALL_GetValue_3,                   NULL,                           NULL,                           B3C_HALL_ReadTrigger,           NULL,           NULL},//SYS_INPUT_GCS_3
    {NULL,               NULL,                          NULL,                                   NULL,                                   NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SM_MDB_CH0
    {NULL,               NULL,                          NULL,                                   NULL,                                   NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SM_MDB_CH1
    {NULL,               NULL,                          NULL,                                   NULL,                                   NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SM_MDB_CH2
    {NULL,               NULL,                          NULL,                                   NULL,                                   NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SM_MDB_CH3
    {B3C_SM_ADC_EXP_Init,&B3C_SM_ADC_EXP_SetCalChan0,   &B3C_SM_ADC_EXP_GetChan0_Raw,           &B3C_SM_ADC_EXP_GetChan0,               B3C_SM_ADC_EXP_GetStatus,       B3C_SM_ADC_EXP_TransferDone,    NULL,                           B3C_SM_ADC_EXP_Enable,  B3C_SM_ADC_EXP_Disable},//SYS_INPUT_SM_EXP_CH0
    {NULL,               &B3C_SM_ADC_EXP_SetCalChan1,   &B3C_SM_ADC_EXP_GetChan1_Raw,           &B3C_SM_ADC_EXP_GetChan1,               NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SM_EXP_CH1
    {NULL,               &B3C_SM_ADC_EXP_SetCalChan2,   &B3C_SM_ADC_EXP_GetChan2_Raw,           &B3C_SM_ADC_EXP_GetChan2,               NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_SM_EXP_CH2
    {NULL,               &B3C_SM_ADC_EXP_SetCalChan3,   &B3C_SM_ADC_EXP_GetChan3_Raw,           &B3C_SM_ADC_EXP_GetChan3,               NULL,                           NULL,                           B3C_SM_ADC_EXP_ReadTrigger,     NULL,           NULL},//SYS_INPUT_SM_EXP_CH3
    {B3C_BMS_Init,       NULL,                          &B3C_BMS_GetDataTemperature_Raw,        &B3C_BMS_GetDataTemperature,            B3C_BMS_GetStatus,             B3C_BMS_TransferDone,           NULL,                           NULL,           NULL},//SYS_INPUT_BAT_TEMPERATURE
    {NULL,               NULL,                          &B3C_BMS_GetDataVoltage_Raw,            &B3C_BMS_GetDataVoltage,                NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_BAT_VOLTAGE
    {NULL,               NULL,                          &B3C_BMS_GetDataCurrent_Raw,            &B3C_BMS_GetDataCurrent,                NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_BAT_CURRENT
    {NULL,               NULL,                          &B3C_BMS_GetDataRemainingCapacity_Raw,  &B3C_BMS_GetDataRemainingCapacity,      NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_BAT_REMAINING_CAPACITY
    {NULL,               NULL,                          &B3C_BMS_GetDataBatteryStatus_Raw,      &B3C_BMS_GetDataBatteryStatus,          NULL,                           NULL,                           NULL,                           NULL,           NULL},//SYS_INPUT_BAT_GPIO_STATUS
    {NULL,               NULL,                          &B3C_BMS_GetDataRelativeStateOfCharge_Raw, &B3C_BMS_GetDataRelativeStateOfCharge, NULL,                         NULL,                           B3C_BMS_ReadTrigger,            NULL,           NULL},//SYS_INPUT_REL_STATE_OF_CHARGE
    {B3C_TEMP_EXP_Init,  NULL,                          &B3C_TEMP_EXP_GetTemp_Raw,              &B3C_TEMP_EXP_GetTemp,                  B3C_TEMP_EXP_GetStatus,         B3C_TEMP_EXP_TransfereDone,     B3C_TEMP_EXP_ReadTrigger,       B3C_TEMP_EXP_Enable,    B3C_TEMP_EXP_Disable} //SYS_INPUT_EXP_TEMP
}; 


SInputConfig SInputConfigArr [SYS_NUM_INPUTS] =
{//SensorGroup        SensorUsed     SR,   minWarning   maxWarning   delWarning     minFatal     maxFatal     delFatal  delInputError     cal1        cal2     cal3     cal4                      BIONIC COMM ENG. VALUE                             BIONIC COMM RAW VALUE                        BIONIC COMM STATUS   
  {SYS_SENSOR_MB_ADC,      true,     10,        1.15,        1.25,          10,        1.10,        1.30,         100,            5,        0,   0.000610,       0,       0,                BIONICS_VAR_BASE_MB_ADC_CH0,                  BIONICS_VAR_BASE_MB_ADC_CH0_RAW,           BIONICS_VAR_BASE_MB_ADC_STATUS},//SYS_INPUT_SM_MB_CH0
  {SYS_SENSOR_MB_ADC,      true,     10,        1.70,        1.85,          10,        1.70,        1.95,         100,            5,        0,   0.000610,       0,       0,                BIONICS_VAR_BASE_MB_ADC_CH1,                  BIONICS_VAR_BASE_MB_ADC_CH1_RAW,                                     NULL},//SYS_INPUT_SM_MB_CH1
  {SYS_SENSOR_MB_ADC,      true,     10,        3.20,        3.40,          10,        3.15,        3.45,         100,            5,        0,   0.001221,       0,       0,                BIONICS_VAR_BASE_MB_ADC_CH2,                  BIONICS_VAR_BASE_MB_ADC_CH2_RAW,                                     NULL},//SYS_INPUT_SM_MB_CH2
  {SYS_SENSOR_MB_ADC,      true,     10,        3.20,        3.40,          10,        3.15,        3.45,         100,            5,        0,   0.001221,       0,       0,                BIONICS_VAR_BASE_MB_ADC_CH3,                  BIONICS_VAR_BASE_MB_ADC_CH3_RAW,                                     NULL},//SYS_INPUT_SM_MB_CH3
  {SYS_SENSOR_MB_ADC,      true,     10,        3.20,        3.40,          10,        3.15,        3.45,         100,            5,        0,   0.001221,       0,       0,                BIONICS_VAR_BASE_MB_ADC_CH4,                  BIONICS_VAR_BASE_MB_ADC_CH4_RAW,                                     NULL},//SYS_INPUT_SM_MB_CH4
  {SYS_SENSOR_MB_ADC,      true,     10,        4.80,        5.20,          10,        4.70,        5.20,         100,            5,        0,   0.001526,       0,       0,                BIONICS_VAR_BASE_MB_ADC_CH5,                  BIONICS_VAR_BASE_MB_ADC_CH5_RAW,                                     NULL},//SYS_INPUT_SM_MB_CH5
  {SYS_SENSOR_MB_ADC,      true,     10,        3.20,        3.40,          10,        3.15,        3.45,         100,            5,        0,   0.001221,       0,       0,                BIONICS_VAR_BASE_MB_ADC_CH6,                  BIONICS_VAR_BASE_MB_ADC_CH6_RAW,                                     NULL},//SYS_INPUT_SM_MB_CH6
  {SYS_SENSOR_MB_ADC,      true,     10,           0,         999,           3,           0,         999,          10,            5,        0,   0.001526,       0,       0,                BIONICS_VAR_BASE_MB_ADC_CH7,                  BIONICS_VAR_BASE_MB_ADC_CH7_RAW,                                     NULL},//SYS_INPUT_SM_MB_CH7
  {SYS_SENSOR_IMU,         true,     10,        -200,         200,           3,        -200,         200,          10,            2,        0,          1,       0,       0,           BIONICS_VAR_BASE_LIN_ACC_X_LOCAL,                                             NULL,              BIONICS_VAR_BASE_IMU_STATUS},//SYS_INPUT_SHANK_LIN_ACC_X
  {SYS_SENSOR_IMU,         true,     10,        -200,         200,           3,        -200,         200,          10,            2,        0,          1,       0,       0,           BIONICS_VAR_BASE_LIN_ACC_Y_LOCAL,                                             NULL,                                     NULL},//SYS_INPUT_SHANK_LIN_ACC_y
  {SYS_SENSOR_IMU,         true,     10,        -200,         200,           3,        -200,         200,          10,            2,        0,          1,       0,       0,           BIONICS_VAR_BASE_LIN_ACC_Z_LOCAL,                                             NULL,                                     NULL},//SYS_INPUT_SHANK_LIN_ACC_z
  {SYS_SENSOR_IMU,         true,     10,        -200,         200,           3,        -200,         200,          10,            2,        0,          1,       0,       0,               BIONICS_VAR_BASE_GRAV_VECT_X,                                             NULL,                                     NULL},//SYS_INPUT_SHANK_GRAV_X
  {SYS_SENSOR_IMU,         true,     10,        -200,         200,           3,        -200,         200,          10,            2,        0,          1,       0,       0,               BIONICS_VAR_BASE_GRAV_VECT_Y,                                             NULL,                                     NULL},//SYS_INPUT_SHANK_GRAV_Y
  {SYS_SENSOR_IMU,         true,     10,        -200,         200,           3,        -200,         200,          10,            2,        0,          1,       0,       0,               BIONICS_VAR_BASE_GRAV_VECT_Z,                                             NULL,                                     NULL},//SYS_INPUT_SHANK_GRAV_Z       
  {SYS_SENSOR_CT,          true,      1,         -12,          12,           1,         -15,          15,         100,           20,    25.19,   -0.02197,       0,       0,                  BIONICS_VAR_KNEE_CT_ANGLE,                    BIONICS_VAR_KNEE_CT_ANGLE_RAW,        BIONICS_VAR_KNEE_CT_SENSOR_STATUS},//SYS_INPUT_CT_ANGLE    
  {SYS_SENSOR_CT,          true,      0,           0,      100000,       10000,           0,       10000,       10000,            2,        0,          1,       0,       0,                                       NULL,                                             NULL,                                     NULL},//SYS_INPUT_CT_VIRTUAL_GAIN
  {SYS_SENSOR_CT,          true,      1,        -150,         150,           1,        -200,         200,           1,           20,        0,     3.6985,       0,  0.0274,          BIONICS_VAR_POWER_KNEE_TORQUE_EST,                                             NULL,                                     NULL},//SYS_INPUT_CT_TORQUE
  {SYS_SENSOR_KA,          true,      1,         -10,         140,           1,         -15,         150,           1,           20,   292.88,   -0.02197,       0,       0,         BIONICS_VAR_KNEE_ACTUATOR_POSITION,           BIONICS_VAR_KNEE_ACTUATOR_POSITION_RAW,  BIONICS_VAR_KNEE_ACTUATOR_SENSOR_STATUS},//SYS_INPUT_KNEE_ANGLE
  {SYS_SENSOR_MOTOR_DRIVE, true,      1,      -15000,       15000,           1,      -15000,       15000,           1,           50,        0,          1,       0,       0,   BIONICS_VAR_KNEE_ACTUATOR_APPLIED_TORQUE,     BIONICS_VAR_KNEE_ACTUATOR_APPLIED_TORQUE_RAW,         BIONICS_VAR_KNEE_ACTUATOR_STATUS},//SYS_INPUT_TORQUE_ACTUAL
  {SYS_SENSOR_MOTOR_DRIVE, true,      1,      -15000,       15000,           1,      -15000,       15000,           1,            2,        0,          1,       0,       0,          BIONICS_VAR_KNEE_ACTUATOR_CURRENT,                                             NULL,                                     NULL},//SYS_INPUT_MOTOR_CURRENT
  {SYS_SENSOR_MOTOR_DRIVE, true,      1,         -30,          90,       10000,         -30,         100,       20000,            1,     205,     -0.0518,       0,       0,      BIONICS_VAR_KNEE_ACTUATOR_TEMPERATURE,        BIONICS_VAR_KNEE_ACTUATOR_TEMPERATURE_RAW,                                     NULL},//SYS_INPUT_MOTOR_TEMP
  {SYS_SENSOR_MOTOR_DRIVE, true,      1,         -30,         105,           3,         -30,         110,          10,            1,        0,          0,       0,       0,      BIONICS_VAR_KNEE_ACTUATOR_MOSFET_TEMP,        BIONICS_VAR_KNEE_ACTUATOR_MOSFET_TEMP_RAW,                                     NULL},//SYS_INPUT_MOSFET_TEMP
  {SYS_SENSOR_GCS,         true,      5,        -120,         600,         200,        -120,         600,         200,            1,     -340,       0.01,       0,       0,            BIONICS_VAR_LEG_FORCE_POSTERIOR,              BIONICS_VAR_LEG_FORCE_POSTERIOR_RAW,      BIONICS_VAR_LEG_FORCE_SENSOR_STATUS},//SYS_INPUT_GCS 0
  {SYS_SENSOR_GCS,         true,      5,        -120,         600,         200,        -120,         600,         200,            1,     -330,       0.01,       0,       0,             BIONICS_VAR_LEG_FORCE_ANTERIOR,               BIONICS_VAR_LEG_FORCE_ANTERIOR_RAW,                                     NULL},//SYS_INPUT_GCS 1 
  {SYS_SENSOR_GCS,         true,      5,        -120,         600,         200,        -120,         600,         200,            1,     -305,       0.01,       0,       0,           BIONICS_VAR_LEG_FORCE_ANTERIOR_2,             BIONICS_VAR_LEG_FORCE_ANTERIOR_2_RAW,                                     NULL},//SYS_INPUT_GCS 2 
  {SYS_SENSOR_GCS,         true,      5,        -120,         600,         200,        -120,         600,         200,            1,     -310,       0.01,       0,       0,          BIONICS_VAR_LEG_FORCE_POSTERIOR_2,            BIONICS_VAR_LEG_FORCE_POSTERIOR_2_RAW,                                     NULL},//SYS_INPUT_GCS 3
  {SYS_SENSOR_MDB_ADC,     false,     0,           0,      100000,       10000,           0,      100000,       10000,          100,        0,          1,       0,       0,                                       NULL,                                             NULL,                                     NULL},//SYS_INPUT_SM_MDB_CH0
  {SYS_SENSOR_MDB_ADC,     false,     0,           0,      100000,       10000,           0,      100000,       10000,          100,        0,          1,       0,       0,                                       NULL,                                             NULL,                                     NULL},//SYS_INPUT_SM_MDB_CH1
  {SYS_SENSOR_MDB_ADC,     false,     0,           0,      100000,       10000,           0,      100000,       10000,          100,        0,          1,       0,       0,                                       NULL,                                             NULL,                                     NULL},//SYS_INPUT_SM_MDB_CH2
  {SYS_SENSOR_MDB_ADC,     false,     0,           0,      100000,       10000,           0,      100000,       10000,          100,        0,          1,       0,       0,                                       NULL,                                             NULL,                                     NULL},//SYS_INPUT_SM_MDB_CH3
  {SYS_SENSOR_EXP_ADC,     true,     10,         3.1,         3.4,          10,           3,        3.45,         100,          100,        0,   0.001221,       0,       0,         BIONICS_VAR_POWER_KNEE_EXP_ADC_CH0,           BIONICS_VAR_POWER_KNEE_EXP_ADC_CH0_RAW,    BIONICS_VAR_POWER_KNEE_EXP_ADC_STATUS},//SYS_INPUT_SM_EXP_CH0
  {SYS_SENSOR_EXP_ADC,     true,     10,         4.8,         5.2,          10,         4.7,        5.25,         100,          100,        0,   0.001526,       0,       0,         BIONICS_VAR_POWER_KNEE_EXP_ADC_CH1,           BIONICS_VAR_POWER_KNEE_EXP_ADC_CH1_RAW,                                     NULL},//SYS_INPUT_SM_EXP_CH1
  {SYS_SENSOR_EXP_ADC,     false,    10,           0,      100000,       10000,           0,      100000,       10000,          100,        0,   0.001526,       0,       0,         BIONICS_VAR_POWER_KNEE_EXP_ADC_CH2,           BIONICS_VAR_POWER_KNEE_EXP_ADC_CH2_RAW,                                     NULL},//SYS_INPUT_SM_EXP_CH2
  {SYS_SENSOR_EXP_ADC,     true,     10,           0,      100000,       10000,           0,      100000,       10000,          100,        0,   0.000610,       0,       0,         BIONICS_VAR_POWER_KNEE_EXP_ADC_CH3,           BIONICS_VAR_POWER_KNEE_EXP_ADC_CH3_RAW,                                     NULL},//SYS_INPUT_SM_EXP_CH3
  {SYS_SENSOR_BATTERY,     true,    250,         -15,          58,           2,         -20,          59,           8,            5,        0,          1,       0,       0,       BIONICS_VAR_BASE_BATTERY_TEMPERATURE,                                             NULL,          BIONICS_VAR_BASE_BATTERY_STATUS},//SYS_INPUT_BAT_TEMPERATURE
  {SYS_SENSOR_BATTERY,     true,    250,       23000,       35000,           4,       21600,       38000,           7,            5,        0,         10,       0,       0,           BIONICS_VAR_BASE_BATTERY_VOLTAGE,             BIONICS_VAR_BASE_BATTERY_VOLTAGE_RAW,                                     NULL},//SYS_INPUT_BAT_VOLTAGE
  {SYS_SENSOR_BATTERY,     true,    250,      -15000,       15000,           2,      -20000,       20000,           2,            5,        0,          1,       0,       0,           BIONICS_VAR_BASE_BATTERY_CURRENT,                                             NULL,                                     NULL},//SYS_INPUT_BAT_CURRENT
  {SYS_SENSOR_BATTERY,     true,    250,           0,      100000,       10000,           0,      100000,           2,            5,        0,          1,       0,       0, BIONICS_VAR_BASE_BATTERY_REMAINING_CAPACITY,                                            NULL,                                     NULL},//SYS_INPUT_BAT_REMAINING_CAPACITY   -> BIONICS_VAR_BASE_BATTERY_LEVEL_RAW
  {SYS_SENSOR_BATTERY,     true,    250,           0,       65535,       10000,           0,       65535,           2,            5,        0,          1,       0,       0,             BIONICS_VAR_BASE_BATTERY_STATE,                                             NULL,                                     NULL},//SYS_INPUT_BAT_GPIO_STATUS
  {SYS_SENSOR_BATTERY,     true,    250,          15,         110,          10,          10,         110,           4,            5,        0,          1,       0,       0,             BIONICS_VAR_BASE_BATTERY_LEVEL,                                             NULL,                                     NULL},//SYS_INPUT_REL_STATE_OF_CHARGE
  {SYS_SENSOR_TEMPERATURE, true,  10000,         -15,          73,           2,         -30,          78,           6,            3,        0,          0,       0,       0,               BIONICS_VAR_BASE_TEMPERATURE,                                             NULL,                                     NULL},//SYS_INPUT_EXP_TEMP  
  };


